name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn package --file pom.xml
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.1
      with:
        name: my-artifact
        path: target/*.jar
    - name: Aqua Security Trivy
      run: |
        trivy fs --format table -o trivy-fs.html .
    - name: Official SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@v5.0.0
      env:
        SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
        SONAR_HOST_URL: ${{secrets.SONAR_HOST_URL}}
    - name: install jq
      run: |
        sudo apt-get update && sudo apt-get install jq -y
    - name: SonarQube Quality Gate Check
      uses: SonarSource/sonarqube-quality-gate-action@v1.1.0
      env:
        SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
        SONAR_HOST_URL: ${{secrets.SONAR_HOST_URL}}
      with:
        scanMetadataReportFile: .scannerwork/report-task.txt #
    - name: Docker Setup QEMU
      uses: docker/setup-qemu-action@v3.6.0
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v3.10.0
    - name: docker build
      run: |
        docker build -t vakabinto/boardgame:latest .
    - name: Aqua Security Trivy
      run: |
        trivy image --format table -o trivy-fs.html vakabinto/boardgame:latest
    - name: Docker Login
      uses: docker/login-action@v3.3.0
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
    - name: docker push
      run: |
        docker push vakabinto/boardgame
    
          

          
    

          
